name: GitHub Metrics
on:
  schedule:
    - cron: "0 * * * *" # Run every hour
  workflow_dispatch: # Allow manual trigger
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: myst-blazeio
          template: classic
          filename: assets/metrics.professional.svg
          config_timezone: Asia/Kolkata
          # Introduction plugin
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          # Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Achievements plugin (Simplified to fix error)
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          
          # WakaTime plugin (30 day range)
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_days: 30
          plugin_wakatime_limit: 5
          plugin_wakatime_user: current
          
          # Lines & Followup
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_indepth: yes
