name: Lines Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  lines-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Lines Metrics (Dark)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: myst-blazeio
          template: classic
          filename: assets/metrics.lines.dark.svg
          config_timezone: Asia/Kolkata
          base: ""
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_indepth: yes
          extras_css: |
            h2, .field { color: #00BFFF !important; }
            svg { background: #0d1117 !important; }

      - name: Lines Metrics (Light)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: myst-blazeio
          template: classic
          filename: assets/metrics.lines.light.svg
          config_timezone: Asia/Kolkata
          base: ""
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_indepth: yes
          extras_css: |
            h2, .field { color: #32CD32 !important; }
            svg { background: #ffffff !important; }
